repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/FlamingTempura/bibtex-tidy
  rev: v1.11.0
  hooks:
  - id: bibtex-tidy
    args: ["ref.bib", "--sort=year,author", "--quiet", "--no-escape", "--modify"]
